version: "3.8"

services:
  terraform:
    image: hashicorp/terraform
    container_name: terraform_ec2
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ~/.aws:/root/.aws   # 使用你本地的 AWS credentials
